---
npm:
  platforms: []

docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/open-balena-api
      publish: true
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/open-balena-api:no-systemd
      publish: true
