/**
 * This module replaces certain rules generated by pinejs/SBVR with hand-coded versions, at the
 * abstractSQL level. It mirrors balena-api's `balena-rules-replacement-hack.ts`: the SBVR is
 * written so it parses and documents the intent, and where SBVR generates the wrong SQL we swap in
 * the correct abstractSQL here. It must run AFTER `optimizeSchema` (see `balena.ts`), so the `from`
 * below is the post-optimisation form of each rule.
 */

import type { AbstractSqlModel } from '@balena/abstract-sql-compiler';
import _ from 'lodash';

const replacements = {
	'It is necessary that each application1 that activates a profile name on an application2, is of a class that is equal to "fleet".':
		{
			from: [
				'Body',
				[
					'Equals',
					[
						'SelectQuery',
						['Select', [['Count', '*']]],
						['From', ['Alias', ['Table', 'application'], 'application.0']],
						['From', ['Alias', ['Table', 'application'], 'application.2']],
						[
							'From',
							[
								'Alias',
								['Table', 'application profile'],
								'application.0-activates-profile name.1-on-application.2',
							],
						],
						[
							'Where',
							[
								'And',
								[
									'Equals',
									[
										'ReferencedField',
										'application.0-activates-profile name.1-on-application.2',
										'on-application',
									],
									['ReferencedField', 'application.0', 'id'],
								],
								[
									'Equals',
									[
										'ReferencedField',
										'application.0-activates-profile name.1-on-application.2',
										'on-application',
									],
									['ReferencedField', 'application.2', 'id'],
								],
								[
									'Not',
									[
										'And',
										[
											'Equals',
											['Text', 'fleet'],
											['ReferencedField', 'application.0', 'is of-class'],
										],
										[
											'Exists',
											['ReferencedField', 'application.0', 'is of-class'],
										],
									],
								],
							],
						],
					],
					['Number', 0],
				],
			],
			to: [
				'Body',
				[
					'Equals',
					[
						'SelectQuery',
						['Select', [['Count', '*']]],
						['From', ['Alias', ['Table', 'application'], 'application.0']],
						[
							'From',
							[
								'Alias',
								['Table', 'application profile'],
								'application.0-activates-profile name.1-on-application.2',
							],
						],
						[
							'Where',
							[
								'And',
								[
									'Equals',
									[
										'ReferencedField',
										'application.0-activates-profile name.1-on-application.2',
										'application',
									],
									['ReferencedField', 'application.0', 'id'],
								],
								[
									'Not',
									[
										'And',
										[
											'Equals',
											['Text', 'fleet'],
											['ReferencedField', 'application.0', 'is of-class'],
										],
										[
											'Exists',
											['ReferencedField', 'application.0', 'is of-class'],
										],
									],
								],
							],
						],
					],
					['Number', 0],
				],
			],
		},
} satisfies {
	[rule: string]: {
		from: AbstractSqlModel['rules'][number][1];
		to: AbstractSqlModel['rules'][number][1];
	};
};

export const apply = (abstractSql: AbstractSqlModel) => {
	for (const [ruleSE, replacement] of Object.entries(replacements)) {
		const existingRule = abstractSql.rules.find((r) => r[2][1] === ruleSE);
		if (existingRule == null) {
			throw new Error(`Could not find rule to replace: ${ruleSE}`);
		}
		if (!_.isEqual(existingRule[1], replacement.from)) {
			throw new Error(
				`Rule's abstract sql does not match the expected for: ${ruleSE}`,
			);
		}
		existingRule[1] = replacement.to;
	}
};
